source 'https://github.com/CocoaPods/Specs'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target "ParseJSON", :exclusive => true do
pod 'Alamofire'
pod 'Argo'
pod 'Result'
pod 'TraktModels', :git => 'https://github.com/marcelofabri/TraktModels.git'
end